@startuml
autonumber

actor User

boundary UI
control Controller
entity SaveManager
entity City
database SaveRepository

User -> UI : saveGame()

UI -> Controller : saveGame()

Controller -> SaveManager : save(city)

SaveManager -> City : getSaveData()
City --> SaveManager : saveData

SaveManager -> SaveRepository : write(saveData)
SaveRepository --> SaveManager : saved

SaveManager --> Controller : saveCompleted()

Controller --> UI : showSaveSuccess()

UI --> User : save confirmed

@enduml
