@startuml
autonumber

actor User

boundary UI
control SaveController
entity SaveManager
entity City
database SaveRepository

User -> UI : saveGame()

UI -> SaveController : saveGame()

SaveController -> SaveManager : save(city)

SaveManager -> City : getSaveData()
City --> SaveManager : saveData

SaveManager -> SaveRepository : write(saveData)
SaveRepository --> SaveManager : saved

SaveManager --> SaveController : saveCompleted()

SaveController --> UI : showSaveSuccess()

UI --> User : save confirmed

@enduml